# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
