# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-25 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170224_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
