# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-25 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_album_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='src',
            field=models.URLField(default='https://i.imgur.com/5EMmiqE.png', max_length=1000),
            preserve_default=False,
        ),
    ]
