# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_media_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Album'),
            preserve_default=False,
        ),
    ]
