# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170314_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.MediaTag'),
        ),
    ]
