# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_account_profile_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='src',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
