# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-07 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170507_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
