# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170507_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedContentItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('image', 'img'), ('video', 'vid'), ('link', 'link'), ('topic', 'topic'), ('blogpost', 'blgpst')], max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='media',
            name='src',
        ),
        migrations.AlterField(
            model_name='album',
            name='access_level',
            field=models.CharField(choices=[('0', 'GUEST'), ('1', 'USER'), ('4', 'FRIEND'), ('5', 'MODERATOR'), ('9', 'ADMIN')], max_length=1),
        ),
        migrations.AddField(
            model_name='feedcontentitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.FeedContentItemType'),
        ),
        migrations.AddField(
            model_name='feedcontentitem',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='content_types',
            field=models.ManyToManyField(related_name='_feed_content_types_+', to='api.FeedContentItemType'),
        ),
        migrations.AddField(
            model_name='feed',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
