# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180503_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='content',
            field=models.ManyToManyField(related_name='_feed_content_+', to='api.FeedContentItem'),
        ),
    ]
