# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 03:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180503_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
