# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 18:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_groupforum'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupforum',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='groupforum',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=[], size=None),
        ),
    ]
