# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180503_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.FeedContentItem')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Discussion')),
            ],
        ),
        migrations.AlterField(
            model_name='feedcontentitemtype',
            name='name',
            field=models.CharField(choices=[('image', 'img'), ('video', 'vid'), ('link', 'link'), ('topic', 'topic'), ('post', 'post'), ('blogpost', 'blgpst')], max_length=6),
        ),
    ]
