# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180507_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedcontentitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=models.ManyToManyField(related_name='feeds', to='api.FeedContentItem'),
        ),
    ]
