# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180508_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('children', models.ManyToManyField(related_name='_interest_children_+', to='api.Interest')),
                ('parents', models.ManyToManyField(related_name='_interest_parents_+', to='api.Interest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='feedcontentitem',
            name='interests',
            field=models.ManyToManyField(to='api.Interest'),
        ),
    ]
