# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-10 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180509_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='interests',
            field=models.ManyToManyField(blank=True, to='api.Interest'),
        ),
        migrations.AlterField(
            model_name='feedcontentitem',
            name='interests',
            field=models.ManyToManyField(blank=True, to='api.Interest'),
        ),
    ]
