# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-11 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180510_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(default='Welcome to my profile!', max_length=140)),
                ('description', models.TextField(blank=True)),
                ('interests', models.ManyToManyField(blank=True, to='api.Interest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile_details',
        ),
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_account_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
