# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-12 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180511_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
