# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-14 22:35
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
