# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-15 19:41
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_group_default(apps, schema_editor):
    alias = schema_editor.connection.alias
    Discussions = apps.get_model('api', 'Discussion').objects.using(alias)
    GroupForums = apps.get_model('api', 'GroupForum').objects.using(alias)

    for discussion in Discussions.all():
        group = GroupForums.filter(feed=discussion.content_item.feeds.first()).first()
        if group:
            discussion.group = group
            discussion.save()
        else:
            discussion.delete()

def backwards_group_default(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180515_1928'),
    ]

    operations = [
        migrations.RunPython(
            forwards_group_default,
            backwards_group_default
        )
    ]
