# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-15 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180515_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='content',
        ),
    ]
