# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-16 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_feed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedContentStash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('max_content', models.IntegerField(default=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.ManyToManyField(related_name='_feedcontentstash_content_+', to='api.FeedContentItem')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='stashes',
            field=models.ManyToManyField(related_name='feeds', to='api.FeedContentStash'),
        ),
    ]
