# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-16 21:58
from __future__ import unicode_literals

from django.db import migrations



def forwards_populate_group_stashes(apps, schema_editor):
    alias = schema_editor.connection.alias
    GroupForums = apps.get_model('api', 'GroupForum').objects.using(alias)
    FeedContentStashes = apps.get_model('api', 'FeedContentStash').objects.using(alias)


    for group in GroupForums.filter(feed__stashes__isnull=True):
        stash = FeedContentStashes.create(name="Default", description="Stored content for this group")
        group.feed.stashes.add(stash)


def backwards_populate_group_stashes(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20180516_2115'),
    ]

    operations = [
        migrations.RunPython(
            forwards_populate_group_stashes,
            backwards_populate_group_stashes
        )
    ]
