# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-24 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180522_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupforum',
            name='members',
            field=models.ManyToManyField(related_name='member_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
