# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-29 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180524_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.FeedContentItem')),
            ],
        ),
    ]
