# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-31 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_comment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcontentitem',
            name='origin_stash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_content', to='api.FeedContentStash'),
        ),
    ]
