# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-31 21:13
from __future__ import unicode_literals

from django.db import migrations


def forwards_resolve_origin_stash(apps, schema_editor):
    alias = schema_editor.connection.alias
    Stashes = apps.get_model('api', 'FeedContentStash').objects.using(alias)
    Content = apps.get_model('api', 'FeedContentItem').objects.using(alias)

    for item in Content.filter(origin_stash__isnull=True):
        # Resolve the origin stash
        stash = Stashes.filter(content__in=[item]).first()
        if stash:
            print(stash)
            item.origin_stash = stash
            item.save()


def backwards_resolve_origin_stash(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_feedcontentitem_origin_stash'),
    ]

    operations = [
        migrations.RunPython(
            forwards_resolve_origin_stash,
            backwards_resolve_origin_stash
        )
    ]
