# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-09 03:33
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20180531_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='log',
        ),
        migrations.RemoveField(
            model_name='media',
            name='media_type',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('Img00', 'create_image'), ('Img01', 'read_image'), ('Img02', 'update_image'), ('Img03', 'delete_image'), ('Img04', 'comment_image'), ('Img05', 'save_image'), ('Link00', 'create_link'), ('Link01', 'read_link'), ('Link02', 'update_link'), ('Link03', 'delete_link'), ('Link04', 'comment_link'), ('Link05', 'save_link'), ('Topic00', 'create_topic'), ('Topic01', 'read_topic'), ('Topic02', 'update_topic'), ('Topic03', 'delete_topic'), ('Topic05', 'save_topic'), ('Post00', 'create_post'), ('Post02', 'update_post'), ('Post03', 'delete_post'), ('Post05', 'save_post'), ('BlogP00', 'create_blogpost'), ('BlogP01', 'read_blogpost'), ('BlogP02', 'update_blogpost'), ('BlogP03', 'delete_blogpost'), ('BlogP04', 'comment_blogpost'), ('BlogP05', 'save_blogpost'), ('Int00', 'create_interest'), ('Int02', 'update_interest'), ('Int05', 'save_interest')], default='Img00', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='message',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='_activitylog_subscribed_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
