# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-20 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20180618_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='text_last_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
