# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-12 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_feedcontentitem_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Place')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='places',
            field=models.ManyToManyField(blank=True, to='api.PlaceRestriction'),
        ),
        migrations.AddField(
            model_name='feedcontentitem',
            name='places',
            field=models.ManyToManyField(blank=True, to='api.PlaceRestriction'),
        ),
        migrations.AddField(
            model_name='profile',
            name='places',
            field=models.ManyToManyField(blank=True, to='api.PlaceRestriction'),
        ),
    ]
