# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-21 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_feedcontentitem_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedContentStashItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('interests', models.ManyToManyField(blank=True, to='api.Interest')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeedContentItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('default_feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Feed')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Place')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedcontentstash',
            name='content'
        ),
        migrations.AddField(
            model_name='feedcontentstash',
            name='content',
            field=models.ManyToManyField(related_name='_feedcontentstash_content_+', through='api.FeedContentStashItem', to='api.FeedContentItem'),
        ),
        migrations.AddField(
            model_name='feedcontentstashitem',
            name='places',
            field=models.ManyToManyField(blank=True, to='api.Place'),
        ),
        migrations.AddField(
            model_name='feedcontentstashitem',
            name='stash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeedContentStash'),
        ),
        migrations.AddField(
            model_name='feed',
            name='places',
            field=models.ManyToManyField(blank=True, to='api.Place'),
        ),
        migrations.AddField(
            model_name='feedcontentitem',
            name='places',
            field=models.ManyToManyField(blank=True, to='api.Place'),
        ),
        migrations.AddField(
            model_name='profile',
            name='places',
            field=models.ManyToManyField(blank=True, to='api.Place'),
        ),
    ]
