# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-03 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20180702_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placerestriction',
            name='max_distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
