# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20180712_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='places',
            field=models.ManyToManyField(blank=True, to='api.Place'),
        ),
        migrations.AlterField(
            model_name='feedcontentitem',
            name='places',
            field=models.ManyToManyField(blank=True, to='api.Place'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='places',
            field=models.ManyToManyField(blank=True, to='api.Place'),
        ),
    ]
