# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20180721_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='background_color',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='feed',
            name='background_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='background_repeat',
            field=models.CharField(blank=True, choices=[('REPEAT', 'repeat'), ('REPEATX', 'repeat-x'), ('REPEATY', 'repeat-y'), ('NOREPEAT', 'no-repeat'), ('SPACE', 'space'), ('ROUND', 'round')], max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='background_color',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='background_repeat',
            field=models.CharField(blank=True, choices=[('REPEAT', 'repeat'), ('REPEATX', 'repeat-x'), ('REPEATY', 'repeat-y'), ('NOREPEAT', 'no-repeat'), ('SPACE', 'space'), ('ROUND', 'round')], max_length=6),
        ),
    ]
