# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20180712_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='default_feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Feed'),
        ),
    ]
