# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20180731_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='default_owner_feed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feed',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
