# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20180731_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='icon',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
