# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-14 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.URLField(blank=True),
        ),
    ]
