# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-14 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20180814_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcontentitemtype',
            name='name',
            field=models.CharField(choices=[('image', 'img'), ('video', 'vid'), ('link', 'link'), ('topic', 'topic'), ('post', 'post'), ('poll', 'poll'), ('blogpost', 'blgpst')], max_length=6),
        ),
    ]
