# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20180814_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcontentstash',
            name='visibility',
            field=models.CharField(choices=[('0', 'Public'), ('1', 'Unlisted'), ('9', 'Private')], default='0', max_length=2),
        ),
    ]
