# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-15 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20180815_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Poll'),
        ),
        migrations.AlterField(
            model_name='polloptionvote',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='votes', to='api.PollOption'),
        ),
    ]
