# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-19 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_feedcontentstash_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcontentstash',
            name='origin_feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_stashes', to='api.Feed'),
        ),
    ]
