# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-15 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20180815_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polloption',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='poll',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 8, 15, 19, 59, 11, 911642)),
            preserve_default=False,
        ),
    ]
