# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20180815_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='title',
        ),
    ]
