# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-21 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20180816_0158'),
        ('api', '0056_feedcontentstash_set_origin_feed'),
    ]

    operations = [
    ]
