# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-21 02:56
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(default=api.models.get_default_code, max_length=16, unique=True),
        ),
    ]
