# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-21 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20180821_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], max_length=8)),
                ('title', models.CharField(max_length=16)),
                ('max_places', models.IntegerField(default=0)),
                ('max_feeds', models.IntegerField(default=0)),
                ('max_owned_groups', models.IntegerField(default=0)),
                ('invites_per_month', models.IntegerField(default=0)),
                ('max_feed_interests', models.IntegerField(default=0)),
                ('max_upload_file_size', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Plan'),
        ),
    ]
