# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 00:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20180821_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='feedcontentitem',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='groupforum',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=60),
        ),
    ]
