# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20180822_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloptionvote',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.Poll'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
