# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-30 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20180822_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.Discussion'),
        ),
    ]
