# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-14 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20180830_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(choices=[('Reply00', 'reply_topic'), ('Reply01', 'reply_comment'), ('Comment00', 'comment_content'), ('Comment01', 'comment_profile'), ('Invite00', 'invite_group')], max_length=8)),
                ('message', models.CharField(max_length=255)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.ActivityLog')),
            ],
        ),
    ]
