# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-14 23:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_owned_topic', models.BooleanField(default=True)),
                ('reply_posted_topic', models.BooleanField(default=True)),
                ('reply_comment', models.BooleanField(default=True)),
                ('reply_profile_comment', models.BooleanField(default=True)),
                ('invite_group', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
