# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-14 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notify_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
