# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-15 02:02
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20181015_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('I', 'instantly'), ('D', 'daily'), ('W', 'weekly'), ('BM', 'bi-monthly'), ('M', 'monthly')], max_length=3)),
                ('web_delivery', models.BooleanField(default=True)),
                ('email_delivery', models.BooleanField(default=True)),
                ('notifications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Reply00', 'reply_topic'), ('Reply01', 'reply_comment'), ('Comment00', 'comment_content'), ('Comment01', 'comment_profile'), ('Invite00', 'invite_group')], max_length=8), size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='activitylogsubscription',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='activitylogsubscription',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ActivityLogSubscription',
        ),
    ]
