# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-21 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20181015_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationsubscription',
            name='current_notifications',
            field=models.ManyToManyField(related_name='_notificationsubscription_current_notifications_+', to='api.Notification'),
        ),
    ]
