# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-21 22:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20181021_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsubscription',
            name='notifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Reply00', 'reply_topic'), ('Reply01', 'reply_comment'), ('Comment00', 'comment_content'), ('Comment01', 'comment_profile'), ('Invite00', 'invite_group')], max_length=12), size=None),
        ),
    ]
