# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-22 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20181021_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subtype',
            field=models.CharField(choices=[('Reply00', 'reply_topic'), ('Reply01', 'reply_comment'), ('Comment00', 'comment_content'), ('Comment01', 'comment_profile'), ('Invite00', 'invite_group')], max_length=12),
        ),
    ]
